### ISSUE TITLE
Switch to interactive `Simulation` environment

### ISSUE THREAD

**Issue by flo-schu** [flo-schu/pymob#30]
Implement the use of an interactive Simulation environment to design models and interact with data. What I mean by this is to instantiate a `SimulationBase()` and then add methods to it that describe the model and observations.

## Tasks

- [ ] This also implies for me to move away from `prepare_casestudy` API. This is really inconvenient most of the time. But the question is whether the use of the CLI API may not require `prepare_casestudy`
- [x] **Increase the modularity of `pymob`case-studies**
- [x] Increase versioning and testing and specify pymob-version in the Simulation
- [ ] This could also address how scenarios are designed. I might be better of to define case studies more often, like `Model 1.0` could be a case study investigating a specific model dynamic. The scenarios are then different datasets, priors, etc. That look at this case study. **THIS IS JUST A VERY QUICK THOUGHT. Think it through before going on with this.** 

## Potential advantages

+ Scenarios used for a paper can be quickly reproduced by copying the entire case study and then used with another model
+ Models are better containerized and can be reused in different contexts
+ Interoperability issue? Should I be able to use the functions and classes of one case study as a imports in another case study (Stichwort: Subclassing of Simulation classes). This way not the entire code needs to be reproduced, but only changes to the previous version are tracked in the code. This, however, also works against the idea of containerization. 
+ Ideally each case study **CAN BE** a separate repository. This way, I can share case-studies and use them as building blocks for new work

**Comment by flo-schu** [comment]
We have 2 APIs
- the case-study API (which takes Simulations as classes and uses modules.)
- There is a more lightweight API (the scripting API), which needs no modules and classes but simply uses the base class to begin Simulating

The idea is that it is realtively easy to migrate from the scripting API to the case-study API when the simulation project becomes large enough to elicit it.

So, the scripting API should help to get started with a model quickly. This is how I am getting started. USE the scripting API and see where the problems lie.

**Comment by flo-schu** [comment]
The case study api is still necessary, as long as Simulations are defined that inherit from the `SimulationBase` class. This could possibly be replaced in the sim.py module with the scripting API, but I question that this will make things better. After all the prepare_casestudy function has shown to work very reliably. 

Alternatively there is a better solution to write functions that make it easy to switch to the new API.
